import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Recipe } from '../Models/recipe.model';

@Injectable({
  providedIn: 'root'
})
export class RecipeService {
  private recipes: Recipe[] = [
    {
      id: 11,
      name: 'Chicken Parmesan',
      description: 'Breaded chicken breasts topped with marinara sauce and mozzarella.',
      image: 'assets/Chicken-Parmesan.jpg',
      category: 'Main Course',
      ingredients: [
        '2 chicken breasts',
        '1 cup breadcrumbs',
        '1/2 cup Parmesan cheese, grated',
        '1 cup marinara sauce',
        '1 1/2 cups mozzarella cheese, shredded',
        '2 tbsp olive oil',
        '1 egg, beaten',
        'Salt and pepper to taste',
      ],
    },
    {
      id: 12,
      name: 'Shrimp Scampi',
      description: 'Juicy shrimp cooked in garlic, butter, and white wine sauce.',
      image: 'assets/Shrimp-Scampi.jpg',
      category: 'Main Course',
      ingredients: [
        '500g shrimp, peeled and deveined',
        '3 tbsp butter',
        '4 cloves garlic, minced',
        '1/4 cup white wine',
        '1 tbsp lemon juice',
        '1/4 cup fresh parsley, chopped',
        '200g linguine pasta',
        'Salt and pepper to taste',
      ],
    },
    {
      id: 13,
      name: 'Fish Tacos',
      description: 'Crispy fish fillets served in soft tortillas with fresh toppings.',
      image: 'assets/Fish-Tacos.jpg',
      category: 'Main Course',
      ingredients: [
        '500g white fish fillets',
        '1 cup flour',
        '1 tsp paprika',
        '1 tsp cumin',
        '1/2 tsp chili powder',
        '2 eggs, beaten',
        '1 cup panko breadcrumbs',
        'Soft tortillas',
        'Cabbage slaw',
        'Lime wedges',
      ],
    },
    {
      id: 14,
      name: 'Spaghetti Carbonara',
      description: 'Pasta tossed with crispy pancetta, eggs, and Parmesan cheese.',
      image: 'assets/Spaghetti-Carbonara.jpg',
      category: 'Main Course',
      ingredients: [
        '200g spaghetti',
        '100g pancetta, diced',
        '2 large eggs',
        '1/2 cup Parmesan cheese, grated',
        '2 cloves garlic, minced',
        'Salt and pepper to taste',
        'Fresh parsley for garnish',
      ],
    },
    {
      id: 15,
      name: 'Eggplant Parmesan',
      description: 'Layers of breaded eggplant slices with marinara and melted cheese.',
      image: 'assets/Eggplant-Parmesan.jpg',
      category: 'Main Course',
      ingredients: [
        '2 eggplants, sliced',
        '1 cup breadcrumbs',
        '1/2 cup Parmesan cheese, grated',
        '1 cup marinara sauce',
        '1 1/2 cups mozzarella cheese, shredded',
        '2 tbsp olive oil',
        '1 egg, beaten',
        'Salt and pepper to taste',
      ],
    },
    {
      id: 16,
      name: 'Beef Wellington',
      description: 'Tender beef fillet coated with mushroom duxelles and wrapped in puff pastry.',
      image: 'assets/Beef-Wellington.jpg',
      category: 'Main Course',
      ingredients: [
        '1 beef tenderloin (about 500g)',
        '2 tbsp olive oil',
        '200g mushrooms, finely chopped',
        '2 tbsp Dijon mustard',
        '12 slices prosciutto',
        '1 sheet puff pastry',
        '1 egg, beaten',
        'Salt and pepper to taste',
      ],
    },
    {
      id: 17,
      name: 'Baked Ziti',
      description: 'Baked pasta with marinara sauce, ricotta, and mozzarella cheese.',
      image: 'assets/Baked-Ziti.jpg',
      category: 'Main Course',
      ingredients: [
        '300g ziti pasta',
        '2 cups marinara sauce',
        '1 cup ricotta cheese',
        '1 1/2 cups mozzarella cheese, shredded',
        '1/2 cup Parmesan cheese, grated',
        '1 tbsp fresh basil, chopped',
        'Salt and pepper to taste',
      ],
    },
    {
      id: 18,
      name: 'Lamb Kofta',
      description: 'Spiced lamb meatballs served with a cooling yogurt sauce.',
      image: 'assets/Lamb-Kofta.jpg',
      category: 'Main Course',
      ingredients: [
        '500g ground lamb',
        '1 onion, finely chopped',
        '2 cloves garlic, minced',
        '1 tsp cumin',
        '1 tsp coriander',
        '1/2 tsp cinnamon',
        '1 tbsp parsley, chopped',
        'Salt and pepper to taste',
        'Yogurt sauce for serving',
      ],
    },
    {
      id: 19,
      name: 'Risotto with Asparagus',
      description: 'Creamy risotto with fresh asparagus and Parmesan cheese.',
      image: 'assets/Risotto-with-Asparagus.jpg',
      category: 'Main Course',
      ingredients: [
        '200g Arborio rice',
        '1 bunch asparagus, chopped',
        '1 onion, chopped',
        '1 cup white wine',
        '4 cups vegetable broth',
        '1/2 cup Parmesan cheese, grated',
        '2 tbsp butter',
        'Salt and pepper to taste',
      ],
    },
    {
      id: 20,
      name: 'Chicken Tikka Masala',
      description: 'Spicy and creamy chicken curry with a blend of aromatic spices.',
      image: 'assets/Chicken-Tikka-Masala.jpg',
      category: 'Main Course',
      ingredients: [
        '500g chicken breast, cubed',
        '1 onion, chopped',
        '2 cloves garlic, minced',
        '1 tbsp ginger, grated',
        '1 tbsp curry powder',
        '1/2 tsp turmeric',
        '1/2 cup heavy cream',
        '1 cup tomato puree',
        '1 tbsp coriander, chopped',
        'Salt and pepper to taste',
      ],
    },
  ];

  getRecipes(): Observable<Recipe[]> {
    return of(this.recipes);
  }

}